import Head from 'next/head';
import Banner from '../components/Banner/Banner';
import Navbar from '../components/Navbar/Navbar';
import Card from '../components/Card/Card';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>NotFlix</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Navbar username='ankita@ank.com' />
      <Banner
        title='Clifford the red dog'
        subTitle='a very cute dog'
        imgUrl='/static/clifford.webp'
      />

      <Card imgUrl='/static/clifford.webp' size='large' />
      <Card imgUrl='/static/clifford.webp' size='medium' />
      <Card imgUrl='/static/clifford.webp' size='small' />
    </div>
  );
}

